# Generated by Django 4.2.6 on 2023-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagenApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('elevacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='media/noaaWebApp')),
                ('audio', models.FileField(null=True, upload_to='media/noaaWebApp')),
            ],
            options={
                'verbose_name': 'ImagenApt',
            },
        ),
    ]
